GitHub Actions WIP

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -1,47 +1,139 @@
 #
 # Workflow: Build Release
 #
-# on push to any release/* branch, build solution, test, build and archive NuGet packages, archive test coverage
-# if pushed with tag v*, publish the corresponding release to NuGet
-
-
 
 name: Build Release Branch
 on:
 
   # build release branch on push to release/* branch
   # where * is expected to be a release version eg 2.1.4
+  # trigger on push to release/<version> branch or push of v<version> tag on that branch
+  # when pushing a tagged commit, only one event triggers, for the tag
   push:
     branches:
       - 'release/*'
+    tags:
+      - 'v*'
 
-  # manually build release branch, optionally release when version matches the branch
-  workflow_dispatch:
-    branches:
-      - 'release/*'
-    inputs:
-      version:
-        description: Copy version (eg "2.1.4") to trigger release. CAREFUL!
-        required: false
-        default: ""
-
-
+  ## manually build release branch, optionally release when version matches the branch
+  #workflow_dispatch:
+  #  branches:
+  #    - 'release/*'
+  #  inputs:
+  #    version:
+  #      description: Copy version (eg "2.1.4") to trigger release. CAREFUL!
+  #      required: false
+  #      default: ""
 
 jobs:
 
+  # verify what has been pushed and determine what to do
+  analyze:
+
+    name: Analyze
+    runs-on: ubuntu-latest
+
+    outputs:
+      todo: ${{ steps.analyze.outputs.todo}}
+      version: ${{ steps.analyze.outputs.version}}
+
+    steps:
+
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Analyze
+        id: analyze
+        shell: bash
+        run: |
+          set +e # don't die whenever a command returns non-zero $?
+
+          echo "Triggered by ${{ github.ref }} at ${{ github.sha }}"
+          HZREF="${{ github.ref }}"
+          HZBRANCH=${HZREF#refs/heads/}
+          
+          if [ "$HZBRANCH" != "$HZREF" ]; then # it is a branch push
+            HZVERSION=${HZBRANCH#release/}
+            if [ "$HZVERSION" != "$HZBRANCH" ]; then # it is a release branch push
+                echo "Triggered by commit in version $HZVERSION release branch $HZBRANCH"
+                git fetch origin refs/tags/v$HZVERSION:refs/tags/v$HZVERSION >/dev/null 2>&1
+                if [ $? -ne 0 ]; then
+                    echo "Tag v$HZVERSION does not exist, proceed"
+                    # set step/job output
+                    echo "::set-output name=todo::build"
+                    echo "::set-output name=version::$HZVERSION"
+                else
+                    HZTAGSHA=$(git rev-parse v$HZVERSION >/dev/null 2>&1)
+                    if [ "$HZTAGSHA" != "${{ github.sha }}" ]; then
+                        echo "::error::Tag v$HZVERSION exists, but on another commit ($HZTAGSHA)"
+                        exit 1
+                    else
+                        echo "Tag v$HZVERSION exists on this commit, nothing to do"
+                        # set step/job output
+                        echo "::set-output name=todo::nothing"
+                        echo "::set-output name=version::$HZVERSION"
+                    fi
+                fi
+            else
+                echo "::error::Triggered by commit in non-release branch $HZBRANCH"
+                exit 1
+            fi
+            exit 0
+          fi
+
+          HZTAG=${HZREF#refs/tags/}
+          if [ "$HZTAG" != "$HZREF" ]; then
+            HZVERSION=${HZTAG#v}
+            if [ "$HZVERSION" != "$HZTAG" ]; then # it is a version tag
+                echo "Triggered by version tag $HZTAG"
+                git fetch origin refs/heads/release/$HZVERSION:refs/heads/release/$HZVERSION >/dev/null 2>&1
+                if [ $? -ne 0 ]; then
+                    echo "::error::Branch release/$HZVERSION does not exist"
+                    exit 1
+                else
+                    HZBRANCHSHA=$(git rev-parse release/$HZVERSION >/dev/null 2>&1)
+                    HZPARENTSHA=$(git rev-parse $HZTAG^1 >/dev/null 2>&1)
+                    if [ "$HZBRANCHSHA" != "$HZPARENTSHA" ]; then
+                      echo "::error::Tag parent is not HEAD of release/$HZVERSION but $HZPARENTSHA"
+                      exit 1
+                    else
+                        echo "Tag parent is HEAD of release/$HZVERSION, proceed"
+                        # set step/job output
+                        echo "::set-output name=todo::release"
+                        echo "::set-output name=version::$HZVERSION"
+                    fi
+                fi
+            else
+                echo "::error::Triggered by non-version tag $HZTAG"
+                exit 1
+            fi
+            exit 0
+          fi
+
+          echo "::error::I am confused"
+          exit 1
+
+
+
   # build and test the release
   build-release:
-    name: Build Release Branch (${{ matrix.os }})
 
+    name: Build Release Branch (${{ matrix.os }})
     runs-on: ${{ matrix.os }}
+
+    needs: analyze
+    if: needs.analyze.outputs.todo != 'nothing'
+
     strategy:
       matrix:
-        os:: [ ubuntu-latest, windows-latest ]
+        os: [ ubuntu-latest, windows-latest ]
 
     steps:
       
-      - name: Install Utilities
-        if: matrix.os == ubuntu-latest
+      - name: Install utilities (Linux only)
+        if: matrix.os == 'ubuntu-latest'
         shell: bash
         run: |
           sudo apt-get update 
@@ -76,6 +168,18 @@ jobs:
         with:
           dotnet-version: '5.0.x'
 
+      ## Install .NET Framework stuff for docfx
+      #- name: Install .NET Framework MSBUILD
+      #  if: matrix.os == 'windows-latest'
+      #  uses: microsoft/setup-msbuild@v1.0.2
+      #  with:
+      #    vs-version: '[15.0,16.0)'
+
+      ## Install .NET Framework stuff for docfx
+      #- name: Install .NET Framework NUGET
+      #  if: matrix.os == 'windows-latest'
+      #  uses: nuget/setup-nuget@v1
+
       # Install Java
       - name: Install JDK
         uses: actions/setup-java@v2
@@ -92,76 +196,71 @@ jobs:
           submodules: true
 
       # configure Git so that we can commit
-      - name: Configure Git
+      - name: Configure repository
         shell: bash
         run: |
           git config user.email "github-actions@hazelcast.com"
           git config user.name "GitHub Actions"
+          dotnet --version
 
-      # gihub.ref is 'refs/heads/release/2.1.4' => need to trim the 'refs/heads/release/' part
-      # there is no workflow-level syntax to do this, so rely on a specific 'run' step to do it
-      - name: Determine version
-        env:
-          HAZELCAST_REF: ${{ github.ref }}
-        shell: bash
-        run: |
-          HAZELCAST_VERSION=${HAZELCAST_REF#refs/heads/release/}
-          echo "HAZELCAST_VERSION=$HAZELCAST_VERSION" >> $GITHUB_ENV
-          echo "HAZELCAST_VERSION=$HAZELCAST_VERSION"
-
-      # determine whether to publish the release
-      - name: Determine whether to publish the release
-        if: github.event_name == 'workflow_dispatch'
-        shell: bash
-        run: |
-          unset HAZELCAST_RELEASE
-          if [ "${{ github.event.inputs.version }}" != "" ]; then
-            if [ "$HAZELCAST_VERSION" == "${{ github.event.inputs.version }}" ]; then 
-              HAZELCAST_RELEASE="RELEASE"; 
-            else
-              echo "::error::Input \"${{ github.event.inputs.version }}\" does not match expected version \"$HAZELCAST_VERSION\""
-            fi
-          fi
-          echo "HAZELCAST_RELEASE=$HAZELCAST_RELEASE" >> $GITHUB_ENV
-          echo "HAZELCAST_RELEASE=$HAZELCAST_RELEASE"
-
-      # version the code
-      # note: setver does nothing if the version is already the current version
-      - name: Version the code
+      # verify the code version
+      - name: Verify the code version
         shell: pwsh
-        run: ./hz.ps1 -version ${{ env.HAZELCAST_VERSION  }} -localRestore setver
+        run: ./hz.ps1 -version ${{ needs.analyze.outputs.version }} -localRestore verify-version
 
       # obtain the snk file required to sign assemblies
       # the snk is avail as secrets.HZ_SNK as a Base64 string
       - name: Obtain assembly signature key
+        id: getsnk
         shell: bash
         run: |
           echo "${{ secrets.HAZELCAST_SNK }}" | base64 -d > ./build/hazelcast.snk 
           ls -l ./build/hazelcast.snk
 
+      # debug
+      # THIS kills the build
+      #- name: DEBUG
+      #  if: matrix.os == 'windows-latest'
+      #  shell: bash
+      #  env:
+      #    MSBuildSDKsPath: 'C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\5.0.300\Sdks'
+      #  run: 
+      #      echo "MSBuildSDKsPath=$MSBuildSDKsPath"
+      #      echo "MSBuildSDKsPath=$MSBuildSDKsPath" >> $GITHUB_ENV
+      #
+      # OK, dotnet installs 2019 (16.x) but docfx can only find 2017 (15.x)
+      # and, 15.x is not installed - can we somehow cheat docfx?
+
       # build signed and reproducible assemblies + docs (skipped on Linux)
       - name: Build
+        id: build
         shell: pwsh
-        run: ./hz.ps1 -localRestore -sign -repro build,docs,pubdocs
+        run: ./hz.ps1 -localRestore -sign -repro build #,docs,pubdocs
 
       # clear the snk file
       - name: Clear assembly signature key
-        if: success() || failure() # always
+        if: (success() || failure()) && steps.getsnk.conclusion == 'success'
         shell: bash
         run: |
           if [ -f ./build/hazelcast.snk ]; then rm ./build/hazelcast.snk; fi
 
       # test (with coverage)
       - name: Test
+        id: test
         env:
           HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
         shell: pwsh
-        run: ./hz.ps1 -noRestore -localRestore -cover -enterprise tests
+        run: ./hz.ps1 -noRestore -localRestore -cover -enterprise -test HazelcastTests.Succeed test
 
       # report
+      # note: from test-reporter README, "Check Runs are created for specific commit SHA. 
+      # It's not possible to specify under which workflow test report should belong if more
+      # workflows are running for the same SHA. Thanks to this GitHub "feature" it's possible 
+      # your test report will appear in an unexpected place in GitHub UI." -- so, when we
+      # trigger a manual run on the same SHA without pushing, 
       - name: Report
         uses: dorny/test-reporter@v1
-        if: success() || failure()
+        if: (success() || failure()) && steps.build.conclusion == 'success'
         with:
           name: Test Results (${{ matrix.os }})
           path: temp/tests/results/results-*.trx
@@ -180,7 +279,7 @@ jobs:
       # create nuget packages
       - name: Pack NuGet packages
         shell: pwsh
-        run: ./hz.ps1 -noRestore -localRestore nupack
+        run: ./hz.ps1 -noRestore -localRestore pack-nuget
 
       # upload nuget packages
       - name: Archive NuGet packages artifact
@@ -189,44 +288,145 @@ jobs:
           name: NuGet-Packages (${{ matrix.os }})
           path: './temp/output/Hazelcast.Net.*pkg'
 
+      ## create docs patch
+      #- name: Create docs patch
+      #  if: matrix.os == 'windows-latest'
+      #  shell: bash
+      #  run: |
+      #    mkdir ./temp/gh-pages-patches
+      #    git -C ./temp/gh-pages format-patch -1 -o ./temp/gh-pages-patches
+
+      ## archive docs patch
+      #- name: Archive docs patch artifact
+      #  if: matrix.os == 'windows-latest'
+      #  uses: actions/upload-artifact@v2
+      #  with:
+      #    name: Docs-Patch (${{ matrix.os }})
+      #    path: './temp/gh-pages-patches/'
 
 
-  # 
+
+  # publish the release
+  # if the build and tests were successful
+  # TODO: and, if we do want to release?!
   publish-release:
+
     name: Publish Release Branch
     runs-on: ubuntu-latest
-    needs: build-release
-    steps:
-      - name: NotSure
-        run: echo "NotSure"
 
-      # this should happen on Windows
-      # but only if Linux is successful = a third job?
-      # and then... we need to (1) download nuget packages, what about documentation?
+    needs: [ analyze, build-release ]
+    if: needs.analyze.outputs.todo == 'release'
+
+    steps:
+
+      - name: Install Utilities (Linux only)
+        shell: bash
+        run: |
+          sudo apt-get update 
+          # ubuntu-latest does not have proper git installed so we have to install it
+          sudo apt-get install --yes --no-install-recommends \
+            git
+          # we need various misc stuff
+          sudo apt-get install --yes --no-install-recommends \
+            wget \
+            curl \
+            apt-transport-https \
+            software-properties-common
+          # we need pwsh
+          wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
+          sudo dpkg -i packages-microsoft-prod.deb
+          rm packages-microsoft-prod.deb
+          sudo apt-get update
+          sudo add-apt-repository universe
+          sudo apt-get install -y powershell
+
+      # Install .NET (minimal, for pushing to NuGet)
+      - name: Install .NET 5.0.x
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: '5.0.x'
+
+      # checkout the hazelcast/hazelcast-csharp-client repository
+      # including all submodules, we are going to need them
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          submodules: true
+
+      # configure Git so that we can commit
+      - name: Configure repository
+        shell: bash
+        run: |
+          git config user.email "github-actions@hazelcast.com"
+          git config user.name "GitHub Actions (Build Release)"
 
       ## tag the release
       #- name: Tag the release
-      #  if: success() && env.HAZELCAST_RELEASE == 'RELEASE'
       #  shell: pwsh
-      #  run: ./hz.ps1 -noRestore -localRestore tagver
+      #  run: |
+      #    ./hz.ps1 -localRestore tag-version
 
-      ## publish nuget packages
-      #- name: Publish NuGet packages
-      #  if: success() && env.HAZELCAST_RELEASE == 'RELEASE'
-      #  shell: pwsh
-      #  env:
-      #    NUGET_API_KEY: ${{ secrets.HAZELCAST_NUGET_API_KEY }}
-      #  run: ./hz.ps1 -noRestore -localRestore nupush
+      ## push & close the branch
+      #- name: Push tag & close branch
+      #  shell: bash
+      #  run: |
+      #    echo DRY   git push origin --tags
+      #    echo DRY   git push origin :release/${{ needs.build-release.outputs.release }}
+
+      # prepare for artifacts
+      - name: Prepare for artifacts
+        shell: bash
+        run: |
+          mkdir ./temp
+          mkdir ./temp/output
+          mkdir ./temp/gh-pages-patches
+
+      # download nuget packages
+      - name: Download NuGet packages artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: NuGet-Packages (windows-latest)
+          path: ./temp/output
+
+      ## download docs patch artifact
+      #- name: Download docs patch artifact
+      #  uses: actions/download-artifact@v2
+      #  with:
+      #    name: Docs-Patch (windows-latest)
+      #    path: ./temp/gh-pages-patches
+
+      # verify downloads
+      - name: Verify downloads
+        shell: bash
+        run: |
+          pwd
+          ls ./temp/output
+          #ls ./temp/gh-pages-patches
+
+      # publish nuget package
+      - name: Publish NuGet packages
+        shell: pwsh
+        env:
+          NUGET_API_KEY: ${{ secrets.HAZELCAST_NUGET_API_KEY }}
+        run: |
+          ./hz.ps1 -noRestore -localRestore push-nuget
 
       ## publish documentation
-      #- name: Publish documentation
-      #  if: success() && env.HAZELCAST_RELEASE == 'RELEASE'
-      #  run: git -C ./temp/gh-pages push origin gh-pages
+      #- name: Publish Documentation
+      #  shell: bash
+      #  run: |
+      #    git clone . ./temp/gh-pages
+      #    git -C ./temp/gh-pages config user.email "github-actions@hazelcast.com"
+      #    git -C ./temp/gh-pages config user.name "GitHub Actions (Build Release)"
+      #    git -C ./temp/gh-pages remote set-url origin https://github.com/hazelcast/hazelcast-csharp-client.git
+      #    git -C ./temp/gh-pages fetch origin gh-pages
+      #    git -C ./temp/gh-pages checkout gh-pages
+      #    git -C ./temp/gh-pages am ./temp/patches/*.patch
+      #    echo DRY   git -C ./temp/gh-pages push origin gh-pages
 
-      # TODO
-      # the final release should be done on Windows else we won't have documentation!
-      # need to figure out the GitHub token so we can push back to the repo
-      # what becomes of the release branch?
-
-
-    
+      # trash the release branch
+      - name: Close release branch
+        shell: bash
+        run: |
+          git push origin :release/${{ needs.analyze.outputs.version }}
